global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "woservice"
    static_configs:
      - targets: ["wo-service:8091"]
        labels:
          instance: wo-service
    scrape_interval: 5s

  - job_name: "simulator"
    static_configs:
      - targets: ["simulator:8092"]
        labels:
          instance: simulator
    scrape_interval: 5s

